### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by BLAST1718** [ByAlperenS/GiftPackage#3]
make it so it can suupportcommand like/minions miner {player}

**Comment by ByAlperenS** [comment]
Hmm, Okey

**Comment by BLAST1718** [comment]
yey
can i suggest next pl u make??

**Comment by ByAlperenS** [comment]
Of course

**Comment by BLAST1718** [comment]
a crate pl which can support commands too and give permission or a lootblx pl which u can have an iteam them if click u will get animations thta support commands

**Comment by BLAST1718** [comment]
?

**Comment by ByAlperenS** [comment]
Write to my Discord account

**Comment by ByAlperenS** [comment]
ByAlperenS#5361
